use siakad;

ALTER TABLE guru ADD kode_mapel VARCHAR(12) AFTER nip;
ALTER TABLE  b_indo ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  b_ing ADD kode_mapel VARCHAR(12) PRIMARY KEY  AFTER nis;
ALTER TABLE  matematika ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  sejarah_indo ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  b_arab ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  quran_hadis ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  akidah_akhlak ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  fikih ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  seni_budaya ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  penjas ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  prakarya_kewirausahaan ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  geografi ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  sejarah ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  ekonomi_p ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  fisika_p ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  kimia_p ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
ALTER TABLE  b_jerman_p ADD kode_mapel VARCHAR(12) PRIMARY KEY AFTER nis;
