use siakad;

ALTER TABLE  b_indo MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  b_ing MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  matematika MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  sejarah_indo MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  b_arab MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  quran_hadis MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  akidah_akhlak MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  fikih MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  seni_budaya MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  penjas MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  prakarya_kewirausahaan MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  geografi MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  sejarah MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  ekonomi_p MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  fisika_p MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  kimia_p MODIFY nis VARCHAR(12) FOREIGN KEY;
ALTER TABLE  b_jerman_p MODIFY nis VARCHAR(12) FOREIGN KEY;
